### ISSUE TITLE
how to train a formation

### ISSUE THREAD

**Issue by bestpredicts** [helios-base/fedit2#11]
I see that fedit2 provides a training function, but I don't know how to use it. Can you provide some documents or examples?

**Comment by hidehisaakiyama** [comment]
Unfortunately, there is no documentation on how to use fedit2.
I assume the latest version fedit2 uses only the triangulation-based formation model.
If you add the data to the field, the resulting model will be calculated and visualized immediately.
See, "HELIOS Base: An Open Source Package for the RoboCup Soccer 2D Simulation" http://dx.doi.org/10.1007/978-3-662-44468-9_46 and "Multi-Agent Positioning Mechanism in the Dynamic Environment" https://doi.org/10.1007/978-3-540-68847-1_38 in detail.
